### ISSUE TITLE
Bug: Repeating elements: all language variants in one language

### ISSUE THREAD

**Issue by alsodenn** [Gregor-Agnes/mask_kesearch_indexer#12] opened 2022-07-06 17:14 UTC
TYPO3: 11.5.12
mask: 7.2.6
mask_kesearch_indexer: 2.1.0

My TYPO3 installation has 3 languages. I have a mask content element with repeating items in it. With these content elements, the content of all three languages ends up in the index of one language.

So I have the content of all 3 languages together in the content index in each individual language. I hope it is understandable what the problem is. :-).

**Comment by Gregor-Agnes** [comment] 2022-07-07 06:38
Hm, is the mask-element translated too? If not, could try with a translated mask-element?

**Comment by alsodenn** [comment] 2022-07-07 08:09
The mask element is translated. All 3 languages are saved in the same language index.

I hope my screenshot clarifies my problem.
![screenshot-mask](https://user-images.githubusercontent.com/906053/177724486-4b217e1c-4a98-4adf-884d-704e0c6107ec.jpg)

**Comment by Gregor-Agnes** [comment] 2022-07-07 09:11
Ok. I am very busy at the moment and on the eve of holiday. I have to look into it later, sorry. In the meantime, feel free to figure out what the problem is. Pull request are always welcome! :)

**Comment by Nwm-Justin** [comment] 2022-11-15 12:09
@alsodenn I have the same problem as you. have you gotten any updates for this issue so far? or have you maybe solved it by yourself?

**Comment by alsodenn** [comment] 2022-11-15 12:15
@Justin-Rundel unfortunately no

**Comment by nwm-dev** [comment] 2022-11-21 17:01
@Gregor-Agnes I just created a pull request (https://github.com/Gregor-Agnes/mask_kesearch_indexer/pull/13). In our instance it worked out, other people may feel free to check the functionality in their instances.

**Comment by Gregor-Agnes** [comment] 2022-11-22 14:36
Fixed by [12](https://github.com/Gregor-Agnes/mask_kesearch_indexer/issues/12), thx to @nwm-dev

**Closed as completed by Gregor-Agnes** 2022-11-22 14:36 UTC
